<a href="https://colab.research.google.com/github/wanlichen2024/gdda612_project1/blob/main/604_assessment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [5]:
from collections import defaultdict

# Task A- Data Transformation

In [6]:
# a. loading dataset
df= pd.read_csv('/content/drive/MyDrive/604 Data Collection/Sales_Sample_Public_Dataset.csv',encoding='ISO-8859-1')

In [7]:
# b. show first few rows
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/07/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/01/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [8]:
df.shape

(2823, 25)

In [9]:
df=pd.DataFrame(df)

In [10]:
# c.handle missing value
df.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [11]:
missing_value_rows= df[df.isnull().any(axis=1)]
missing_value_rows

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/07/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/01/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/01/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/06/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [12]:
#1.  add non null value of 'ADDRESSLINE2' to 'ADDRESSLINE1', and drop 'ADDRESSLINE2' columns
df['ADDRESSLINE1'] = df.apply(lambda row: f"{row['ADDRESSLINE1']}, {row['ADDRESSLINE2']}" if pd.notna(row['ADDRESSLINE2']) else row['ADDRESSLINE1'], axis=1)
df.drop('ADDRESSLINE2', axis=1, inplace=True)

In [13]:
#2. fill 'TERRITORY' with unknown
df['TERRITORY']= df['TERRITORY'].fillna('Unknown')

In [14]:
# 3. machine learning fulfil missing value

In [15]:
df1= df[['COUNTRY','STATE','CITY']]

In [16]:
# seperate the countries with state and the countries without state
countries_with_state = df1[df1['STATE'].notna()]['COUNTRY'].unique()
df_with_state = df1[df1['COUNTRY'].isin(countries_with_state)]
df_without_state = df1[~df1['COUNTRY'].isin(countries_with_state)]

#fill df_without_state with 'NONE'
df_without_state['STATE'] = 'NONE'

# encode city and country columns
label_encoders = {}
for column in ['CITY', 'COUNTRY']:
    le = LabelEncoder()
    df_with_state[column] = le.fit_transform(df_with_state[column].astype(str))
    label_encoders[column] = le

# seperate the countries with state with missing value and without missing value
df_known = df_with_state[df_with_state['STATE'].notna()]
df_unknown = df_with_state[df_with_state['STATE'].isna()]

# encode state column for the country's state without missing vlaue
state_le = LabelEncoder()
df_known['STATE'] = state_le.fit_transform(df_known['STATE'])

# setting x as feature columns and y= state as the target column
X = df_known.drop(columns=['STATE'])
y = df_known['STATE']

# trainning model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier()
model.fit(X_train, y_train)

# fill missing value
X_unknown = df_unknown.drop(columns=['STATE'])
predicted_states = model.predict(X_unknown)
predicted_states_labels = state_le.inverse_transform(predicted_states)

# convert predict value to original string
df_unknown['STATE'] = predicted_states_labels

# convert all columns to original string
for column, le in label_encoders.items():
    df_known[column] = le.inverse_transform(df_known[column])
    df_unknown[column] = le.inverse_transform(df_unknown[column])

df_known['STATE'] = state_le.inverse_transform(df_known['STATE'])

# combine data frame
df_combined = pd.concat([df_known, df_unknown, df_without_state], ignore_index=True)

<ipython-input-16-4f783ae48221>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_without_state['STATE'] = 'NONE'
<ipython-input-16-4f783ae48221>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_with_state[column] = le.fit_transform(df_with_state[column].astype(str))
<ipython-input-16-4f783ae48221>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_with_state[column] = le.fit_transform(df_with_state[column].astype(str))
<ipython-input-16-4f783ae48221>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_known['STATE'] = state_le.fit_transform(df_known['STATE'])
<ipython-input-16-4f783ae48221>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unknown['STATE'] = predicted_states_labels
<ipython-input-16-4f783ae48221>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_known[column] = le.inverse_transform(df_known[column])
<ipython-input-16-4f783ae48221>:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unknown[column] = le.inverse_transform(df_unknown[column])
<ipython-input-16-4f783ae48221>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_known[column] = le.inverse_transform(df_known[column])
<ipython-input-16-4f783ae48221>:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unknown[column] = le.inverse_transform(df_unknown[column])
<ipython-input-16-4f783ae48221>:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_known['STATE'] = state_le.inverse_transform(df_known['STATE'])

In [17]:
df_combined.isnull().sum()

COUNTRY    0
STATE      0
CITY       0
dtype: int64

In [18]:
#combine df_unknown and df_known
df_combined = pd.concat([df_known, df_unknown, df_without_state], ignore_index=False)
df_combined

      COUNTRY STATE           CITY
0         USA    NY            NYC
3         USA    CA       Pasadena
4         USA    CA  San Francisco
5         USA    CA     Burlingame
8         USA    CA  San Francisco
...       ...   ...            ...
2816  Denmark  NONE      Kobenhavn
2818    Spain  NONE         Madrid
2819  Finland  NONE           Oulu
2820    Spain  NONE         Madrid
2821   France  NONE       Toulouse

[2823 rows x 3 columns]

In [19]:
# fill df 'STATE' based on df_combined
df['STATE']= df['STATE'].fillna(df_combined['STATE'])

In [20]:
df.isnull().sum()

ORDERNUMBER          0
QUANTITYORDERED      0
PRICEEACH            0
ORDERLINENUMBER      0
SALES                0
ORDERDATE            0
STATUS               0
QTR_ID               0
MONTH_ID             0
YEAR_ID              0
PRODUCTLINE          0
MSRP                 0
PRODUCTCODE          0
CUSTOMERNAME         0
PHONE                0
ADDRESSLINE1         0
CITY                 0
STATE                0
POSTALCODE          76
COUNTRY              0
TERRITORY            0
CONTACTLASTNAME      0
CONTACTFIRSTNAME     0
DEALSIZE             0
dtype: int64

In [21]:
# fill postalcode with each city most common code
def most_common_or_default(series):
    try:
        return series.value_counts().index[0]
    except IndexError:
        return 'Unknown'

most_common_postalcode = df.groupby('CITY')['POSTALCODE'].agg(most_common_or_default).to_dict()

df['POSTALCODE'] = df.apply(lambda row: most_common_postalcode[row['CITY']] if pd.isnull(row['POSTALCODE']) else row['POSTALCODE'], axis=1)

In [22]:
df.isnull().sum()

ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
ORDERLINENUMBER     0
SALES               0
ORDERDATE           0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
ADDRESSLINE1        0
CITY                0
STATE               0
POSTALCODE          0
COUNTRY             0
TERRITORY           0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
dtype: int64

In [23]:
df.dtypes

ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE            object
STATUS               object
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE          object
MSRP                  int64
PRODUCTCODE          object
CUSTOMERNAME         object
PHONE                object
ADDRESSLINE1         object
CITY                 object
STATE                object
POSTALCODE           object
COUNTRY              object
TERRITORY            object
CONTACTLASTNAME      object
CONTACTFIRSTNAME     object
DEALSIZE             object
dtype: object

In [24]:
df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])

In [25]:
#d. choose 'ORDERDATE' column perform sorting techneque asc and des
df.sort_values(by='ORDERDATE', ascending=True, inplace=True)
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PHONE,ADDRESSLINE1,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
578,10100,30,100.00,3,5151.00,2003-01-06,Shipped,1,1,2003,...,6035558647,2304 Long Airport Avenue,Nashua,NH,62005,USA,Unknown,Young,Valarie,Medium
680,10100,50,67.80,2,3390.00,2003-01-06,Shipped,1,1,2003,...,6035558647,2304 Long Airport Avenue,Nashua,NH,62005,USA,Unknown,Young,Valarie,Medium
1267,10100,22,86.51,4,1903.22,2003-01-06,Shipped,1,1,2003,...,6035558647,2304 Long Airport Avenue,Nashua,NH,62005,USA,Unknown,Young,Valarie,Small
2024,10100,49,34.47,1,1689.03,2003-01-06,Shipped,1,1,2003,...,6035558647,2304 Long Airport Avenue,Nashua,NH,62005,USA,Unknown,Young,Valarie,Small
1539,10101,45,31.20,3,1404.00,2003-01-09,Shipped,1,1,2003,...,+49 69 66 90 2555,Lyonerstr. 34,Frankfurt,NONE,60528,Germany,EMEA,Keitel,Roland,Small

In [26]:
df.sort_values(by='ORDERDATE', ascending=False, inplace=True)
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PHONE,ADDRESSLINE1,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
727,10425,38,99.41,7,3777.58,2005-05-31,In Process,2,5,2005,...,40.67.8555,"67, rue des Cinquante Otages",Nantes,NONE,44000,France,EMEA,Labrune,Janine,Medium
239,10424,49,100.00,3,7969.36,2005-05-31,In Process,2,5,2005,...,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,NONE,28034,Spain,EMEA,Freyre,Diego,Large
53,10424,50,100.00,6,12001.00,2005-05-31,In Process,2,5,2005,...,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,NONE,28034,Spain,EMEA,Freyre,Diego,Large
1667,10425,49,100.00,9,5510.54,2005-05-31,In Process,2,5,2005,...,40.67.8555,"67, rue des Cinquante Otages",Nantes,NONE,44000,France,EMEA,Labrune,Janine,Medium
1341,10425,38,100.00,13,4325.16,2005-05-31,In Process,2,5,2005,...,40.67.8555,"67, rue des Cinquante Otages",Nantes,NONE,44000,France,EMEA,Labrune,Janine,Medium

In [27]:
# e. define a conditional filter: filter city as paris order
df_paris = df[df['CITY'] == 'Paris']
df_paris.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PHONE,ADDRESSLINE1,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
828,10402,55,55.72,2,3064.60,2005-04-07,Shipped,2,4,2005,...,(1) 47.55.6555,"25, rue Lauriston",Paris,NONE,75016,France,EMEA,Perrier,Dominique,Medium
1588,10402,59,87.60,3,5168.40,2005-04-07,Shipped,2,4,2005,...,(1) 47.55.6555,"25, rue Lauriston",Paris,NONE,75016,France,EMEA,Perrier,Dominique,Medium
78,10402,45,100.00,1,5833.80,2005-04-07,Shipped,2,4,2005,...,(1) 47.55.6555,"25, rue Lauriston",Paris,NONE,75016,France,EMEA,Perrier,Dominique,Medium
2403,10395,46,100.00,4,5692.96,2005-03-17,Shipped,1,3,2005,...,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,NONE,75508,France,EMEA,Da Cunha,Daniel,Medium
130,10395,32,100.00,2,3370.56,2005-03-17,Shipped,1,3,2005,...,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,NONE,75508,France,EMEA,Da Cunha,Daniel,Medium

In [28]:
# f. create a new column to derive new information
df['CONTACTFULLNAME'] = df['CONTACTFIRSTNAME'] + ' ' + df['CONTACTLASTNAME']
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,CONTACTFULLNAME
727,10425,38,99.41,7,3777.58,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",Nantes,NONE,44000,France,EMEA,Labrune,Janine,Medium,Janine Labrune
239,10424,49,100.00,3,7969.36,2005-05-31,In Process,2,5,2005,...,"C/ Moralzarzal, 86",Madrid,NONE,28034,Spain,EMEA,Freyre,Diego,Large,Diego Freyre
53,10424,50,100.00,6,12001.00,2005-05-31,In Process,2,5,2005,...,"C/ Moralzarzal, 86",Madrid,NONE,28034,Spain,EMEA,Freyre,Diego,Large,Diego Freyre
1667,10425,49,100.00,9,5510.54,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",Nantes,NONE,44000,France,EMEA,Labrune,Janine,Medium,Janine Labrune
1341,10425,38,100.00,13,4325.16,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",Nantes,NONE,44000,France,EMEA,Labrune,Janine,Medium,Janine Labrune

In [30]:
# g. choose a categorical column country and aggregate data
df.groupby('COUNTRY')['SALES'].sum()

COUNTRY
Australia       630623.10
Austria         202062.53
Belgium         108412.62
Canada          224078.56
Denmark         245637.15
Finland         329581.91
France         1110916.52
Germany         220472.09
Ireland          57756.43
Italy           374674.31
Japan           188167.81
Norway          307463.70
Philippines      94015.73
Singapore       288488.41
Spain          1215686.92
Sweden          210014.21
Switzerland     117713.56
UK              478880.46
USA            3627982.83
Name: SALES, dtype: float64